# Generated by Django 5.1.2 on 2024-11-06 07:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('sotildi', 'Sotildi')], max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.category')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('sotildi', 'Sotildi')], max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.category')),
            ],
        ),
    ]
